-- MySQL Script generated by MySQL Workbench
-- Mon Mar  2 13:13:18 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tutoriascomunitarias
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tutoriascomunitarias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tutoriascomunitarias` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `tutoriascomunitarias` ;

-- -----------------------------------------------------
-- Table `tutoriascomunitarias`.`tutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tutoriascomunitarias`.`tutor` (
  `id_tutor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `especialidad` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_tutor`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tutoriascomunitarias`.`disponibilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tutoriascomunitarias`.`disponibilidad` (
  `id_disponibilidad` INT NOT NULL AUTO_INCREMENT,
  `dia` DATE NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fin` TIME NOT NULL,
  `id_tutor` INT NOT NULL,
  PRIMARY KEY (`id_disponibilidad`),
  INDEX `fk_disponibilidad_tutor` (`id_tutor` ASC) VISIBLE,
  CONSTRAINT `fk_disponibilidad_tutor`
    FOREIGN KEY (`id_tutor`)
    REFERENCES `tutoriascomunitarias`.`tutor` (`id_tutor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tutoriascomunitarias`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tutoriascomunitarias`.`estudiante` (
  `id_estudiante` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `grado_escolar` VARCHAR(50) NOT NULL,
  `escuela_procedencia` VARCHAR(100) NOT NULL,
  `telefono_contacto` VARCHAR(15) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  PRIMARY KEY (`id_estudiante`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tutoriascomunitarias`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tutoriascomunitarias`.`materia` (
  `id_materia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `nivel_educativo` VARCHAR(50) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_materia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tutoriascomunitarias`.`sesiontutoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tutoriascomunitarias`.`sesiontutoria` (
  `id_sesion` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `estado_sesion` ENUM('programada', 'en curso', 'completada') NOT NULL,
  `id_tutor` INT NOT NULL,
  `id_estudiante` INT NOT NULL,
  `id_materia` INT NOT NULL,
  PRIMARY KEY (`id_sesion`),
  INDEX `fk_sesion_tutor` (`id_tutor` ASC) VISIBLE,
  INDEX `fk_sesion_estudiante` (`id_estudiante` ASC) VISIBLE,
  INDEX `fk_sesion_materia` (`id_materia` ASC) VISIBLE,
  CONSTRAINT `fk_sesion_estudiante`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `tutoriascomunitarias`.`estudiante` (`id_estudiante`),
  CONSTRAINT `fk_sesion_materia`
    FOREIGN KEY (`id_materia`)
    REFERENCES `tutoriascomunitarias`.`materia` (`id_materia`),
  CONSTRAINT `fk_sesion_tutor`
    FOREIGN KEY (`id_tutor`)
    REFERENCES `tutoriascomunitarias`.`tutor` (`id_tutor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
