package views;

import controllers.MateriaController;

/**
 *
 * @author Ricardo
 */
public class DlgMateria extends javax.swing.JDialog {
    private MateriaController maController;
    /**
     * Creates new form DlgMateria
     */
    public DlgMateria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        maController = new MateriaController();
        cargarTablaMaterias();
    }
    
    private void cargarTablaMaterias(){
        tblMateria.setModel(maController.obtenerTablaMaterias());
    }
    
    private void buscar() {
        String nombre = txtFiltro.getText().trim();
        if (nombre.isEmpty()) {
            cargarTablaMaterias();
        } else {
            tblMateria.setModel(maController.obtenerTablaMateriasFiltro(nombre));
        }
    }
    
    public Integer getMateriaSeleccionada() {
        int fila = tblMateria.getSelectedRow();
        if (fila >= 0) {
            return (Integer) tblMateria.getValueAt(fila, 0); // columna 0 = id
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMateria = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });

        tblMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMateriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMateria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(txtFiltro))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblMateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMateriaMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) { // doble clic
            dispose(); // cierra el diálogo
        }
    }//GEN-LAST:event_tblMateriaMouseClicked

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_txtFiltroKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf Dark look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            javax.swing.UIManager.put("defaultFont", new java.awt.Font("Fira Code", java.awt.Font.PLAIN, 14));
            javax.swing.UIManager.put("control", new java.awt.Color(30, 30, 30));
            javax.swing.UIManager.put("Panel.background", new java.awt.Color(30, 30, 30));
            javax.swing.UIManager.put("RootPane.background", new java.awt.Color(30, 30, 30));
            javax.swing.UIManager.put("Viewport.background", new java.awt.Color(30, 30, 30));
            javax.swing.UIManager.put("OptionPane.background", new java.awt.Color(30, 30, 30));
            
            javax.swing.UIManager.put("Button.arc", 15);
            javax.swing.UIManager.put("Component.arc", 15);
            javax.swing.UIManager.put("TextComponent.arc", 15);
            javax.swing.UIManager.put("ScrollBar.thumbArc", 999);
            javax.swing.UIManager.put("ScrollBar.thumbInsets", new java.awt.Insets(2, 2, 2, 2));
            javax.swing.UIManager.put("Table.selectionBackground", new java.awt.Color(37, 99, 235));
            javax.swing.UIManager.put("Table.alternateRowColor", new java.awt.Color(45, 48, 56));
            javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatDarkLaf());
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(DlgMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgMateria dialog = new DlgMateria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMateria;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
