/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Ricardo
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private JPanel frmActual;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        pnlContenido.setLayout(new CardLayout());
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlContenido = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuPrincipal = new javax.swing.JMenu();
        mnuEstudiantes = new javax.swing.JMenuItem();
        mnuTutores = new javax.swing.JMenuItem();
        mnuSesiones = new javax.swing.JMenuItem();
        mnuMaterias = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnlContenidoLayout = new javax.swing.GroupLayout(pnlContenido);
        pnlContenido.setLayout(pnlContenidoLayout);
        pnlContenidoLayout.setHorizontalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel2)
                .addContainerGap(698, Short.MAX_VALUE))
        );
        pnlContenidoLayout.setVerticalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addContainerGap(590, Short.MAX_VALUE))
        );

        mnuPrincipal.setText("Menus");

        mnuEstudiantes.setText("Estudiantes");
        mnuEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEstudiantesActionPerformed(evt);
            }
        });
        mnuPrincipal.add(mnuEstudiantes);

        mnuTutores.setText("Tutores");
        mnuTutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTutoresActionPerformed(evt);
            }
        });
        mnuPrincipal.add(mnuTutores);

        mnuSesiones.setText("Sesiones");
        mnuSesiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSesionesActionPerformed(evt);
            }
        });
        mnuPrincipal.add(mnuSesiones);

        mnuMaterias.setText("Materias");
        mnuMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMateriasActionPerformed(evt);
            }
        });
        mnuPrincipal.add(mnuMaterias);

        jMenuBar1.add(mnuPrincipal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(pnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEstudiantesActionPerformed
        // TODO add your handling code here:
        if (frmActual != null) {
            pnlContenido.remove(frmActual);
        }
        
        FrmEstudiantes frmEstudiantes = new FrmEstudiantes();
        
        pnlContenido.add(frmEstudiantes, "estudiantes");
        CardLayout cl = (CardLayout) pnlContenido.getLayout();
        cl.show(pnlContenido, "estudiantes");
        
        frmActual=frmEstudiantes;

    }//GEN-LAST:event_mnuEstudiantesActionPerformed

    private void mnuTutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTutoresActionPerformed
        // TODO add your handling code here:
        if (frmActual != null) {
            pnlContenido.remove(frmActual);
        }
        
        FrmTutor frmTutor = new FrmTutor();
        pnlContenido.add(frmTutor, "tutores");
        CardLayout cl = (CardLayout) pnlContenido.getLayout();
        cl.show(pnlContenido, "tutores");
        
        frmActual = frmTutor;
    }//GEN-LAST:event_mnuTutoresActionPerformed

    private void mnuMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMateriasActionPerformed
        // TODO add your handling code here:
        if (frmActual != null) {
            pnlContenido.remove(frmActual);
        }
        
        FrmMaterias frmMaterias = new FrmMaterias();
        
        pnlContenido.add(frmMaterias, "materias");
        CardLayout cl = (CardLayout) pnlContenido.getLayout();
        cl.show(pnlContenido, "materias");
        
        frmActual = frmMaterias;
        
    }//GEN-LAST:event_mnuMateriasActionPerformed

    private void mnuSesionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSesionesActionPerformed
        // TODO add your handling code here:
        if (frmActual != null) {
            pnlContenido.remove(frmActual);
        }
        
        FrmSesiones frmSesiones = new FrmSesiones();
        
        pnlContenido.add(frmSesiones, "sesiones");
        CardLayout cl = (CardLayout) pnlContenido.getLayout();
        cl.show(pnlContenido, "sesiones");
        
        frmActual = frmSesiones;
    }//GEN-LAST:event_mnuSesionesActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf Dark look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            javax.swing.UIManager.put("defaultFont", new java.awt.Font("Fira Code", java.awt.Font.PLAIN, 14));
            
            // VS Code Dark Background (#1E1E1E -> 30, 30, 30)
            javax.swing.UIManager.put("control", new java.awt.Color(30, 30, 30));
            javax.swing.UIManager.put("Panel.background", new java.awt.Color(30, 30, 30));
            javax.swing.UIManager.put("RootPane.background", new java.awt.Color(30, 30, 30));
            javax.swing.UIManager.put("Viewport.background", new java.awt.Color(30, 30, 30));
            javax.swing.UIManager.put("OptionPane.background", new java.awt.Color(30, 30, 30));
            
            // Advanced UI styling
            javax.swing.UIManager.put("Button.arc", 15); // Rounded buttons
            javax.swing.UIManager.put("Component.arc", 15); // Rounded text fields and dropdowns
            javax.swing.UIManager.put("TextComponent.arc", 15); 
            javax.swing.UIManager.put("ScrollBar.thumbArc", 999); // Round thumbs like macOS
            javax.swing.UIManager.put("ScrollBar.thumbInsets", new java.awt.Insets(2, 2, 2, 2));
            javax.swing.UIManager.put("Table.selectionBackground", new java.awt.Color(37, 99, 235)); // Vibrant blue selection
            javax.swing.UIManager.put("Table.alternateRowColor", new java.awt.Color(45, 48, 56)); // Dark alternating rows
            javax.swing.UIManager.put("TabbedPane.selectedBackground", new java.awt.Color(37, 99, 235));
            
            javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatDarkLaf());
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuEstudiantes;
    private javax.swing.JMenuItem mnuMaterias;
    private javax.swing.JMenu mnuPrincipal;
    private javax.swing.JMenuItem mnuSesiones;
    private javax.swing.JMenuItem mnuTutores;
    private javax.swing.JPanel pnlContenido;
    // End of variables declaration//GEN-END:variables
}
